import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mdx from '@astrojs/mdx';

export default defineConfig({
  site: 'https://sergarb1.github.io',
  base: '/ApuntesProyectoDAW',
  integrations: [
    starlight({
      title: 'Apuntes Proyecto Intermodular',
      description: 'Guía Didáctica de Proyecto Intermodular I y II - Desarrollo de Aplicaciones Web (DAW) · Curso 2026-2027',
      logo: {
        src: './src/assets/logo.svg',
        replacesTitle: false,
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/sergarb1/ApuntesProyectoDAW' },
      ],
      editLink: {
        baseUrl: 'https://github.com/sergarb1/ApuntesProyectoDAW/edit/main',
      },
      lastUpdated: true,
      pagination: true,
      pagefind: true,
      tableOfContents: {
        minHeadingLevel: 2,
        maxHeadingLevel: 4,
      },
      customCss: [
        './src/styles/custom.css',
      ],
      head: [
        {
          tag: 'link',
          attrs: {
            rel: 'icon',
            type: 'image/svg+xml',
            href: '/ApuntesProyectoDAW/favicon.svg',
          },
        },
        {
          tag: 'meta',
          attrs: {
            name: 'license',
            content: 'CC BY-SA 4.0',
          },
        },
      ],
      components: {
        Footer: './src/components/Footer.astro',
        Hero: './src/components/Hero.astro',
      },
      sidebar: [
        {
          label: '🏠 Inicio',
          link: '/',
        },
        {
          label: '📚 Guía Didáctica',
          collapsed: false,
          items: [
            { label: '🔄 Continuidad PI1 → PI2', link: '/continuidad' },
            {
              label: '🎯 Proyecto 1 — Bases y Planificación',
              collapsed: false,
              items: [
                { label: '📌 Introducción', link: '/guia-didactica/proyecto-1/' },
                { label: '🎓 Competencias', link: '/guia-didactica/proyecto-1/competencias' },
                {
                  label: '📋 Unidades Didácticas',
                  collapsed: false,
                  items: [
                    { label: '🔍 UD 1.1: MVP', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp' },
                    { label: '🔄 UD 1.2: SCRUM Lite', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite' },
                    { label: '📋 UD 1.3: Requisitos', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos' },
                    { label: '⚙️ UD 1.4: Tecnologías', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias' },
                    { label: '🎤 UD 1.5: Comunicación', link: '/guia-didactica/proyecto-1/uds/u1-5-lenguaje-verbal' },
                    { label: '📄 UD 1.6: Documentación', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion' },
                    { label: '🎯 UD 1.7: Propuesta', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta-proyecto1' },
                  ],
                },
                { label: '✅ Evaluación', link: '/guia-didactica/proyecto-1/evaluacion' },
              ],
            },
            {
              label: '🚀 Proyecto 2 — Desarrollo Avanzado',
              collapsed: false,
              items: [
                { label: '📌 Introducción', link: '/guia-didactica/proyecto-2/' },
                { label: '🎓 Competencias', link: '/guia-didactica/proyecto-2/competencias' },
                {
                  label: '📋 Unidades Didácticas',
                  collapsed: false,
                  items: [
                    { label: '📋 UD 2.1: Requisitos Avanzado', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado' },
                    { label: '🔄 UD 2.2: SCRUM Avanzado', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado' },
                    { label: '🌿 UD 2.3: Git Avanzado', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado' },
                    { label: '🏗️ UD 2.4: Patrones de Diseño', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno' },
                    { label: '📐 UD 2.5: Diagramas', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas' },
                    { label: '🤖 UD 2.6: IA como Copiloto', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto' },
                    { label: '☁️ UD 2.7: Despliegue', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue' },
                    { label: '📊 UD 2.8: Monitorización', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion' },
                    { label: '🚀 UD 2.9: Propuesta Final', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final' },
                  ],
                },
                { label: '📦 Entregables', link: '/guia-didactica/proyecto-2/entregables' },
                { label: '✅ Evaluación', link: '/guia-didactica/proyecto-2/evaluacion' },
              ],
            },
            { label: '⚙️ Metodología', link: '/metodologia' },
            { label: '🛠️ Herramientas', link: '/herramientas' },
            { label: '📖 Recursos', link: '/recursos' },
            { label: '👨‍🏫 Profesores', link: '/profesores' },
            { label: '⚖️ Licencia', link: '/licencia' },
            { label: '❓ Preguntas Frecuentes', link: '/faq' },
            { label: '💡 Ideas para Proyectos', link: '/ideas' },
          ],
        },
        {
          label: '📝 Apuntes',
          collapsed: true,
          items: [
            {
              label: '📓 PI1 - Cómo afrontar el proyecto',
              collapsed: true,
              items: [
                { label: '🚪 Introducción', link: '/apuntes-pi1/' },
                { label: '🗺️ Ruta de aprendizaje', link: '/apuntes-pi1/ruta-aprendizaje' },
                {
                  label: '🧭 U1. Definir el proyecto',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u1-fundamentos-programacion' },
                    { label: '01 · De la idea al proyecto', link: '/apuntes-pi1/u1-fundamentos-programacion/01-de-la-idea-al-proyecto' },
                    { label: '02 · El MVP como mentalidad', link: '/apuntes-pi1/u1-fundamentos-programacion/02-el-mvp-como-mentalidad' },
                    { label: '03 · Las cinco preguntas', link: '/apuntes-pi1/u1-fundamentos-programacion/03-las-cinco-preguntas' },
                    { label: '04 · Objetivos SMART', link: '/apuntes-pi1/u1-fundamentos-programacion/04-objetivos-smart' },
                    { label: '05 · El alcance', link: '/apuntes-pi1/u1-fundamentos-programacion/05-el-alcance' },
                    { label: '06 · Usuario y público objetivo', link: '/apuntes-pi1/u1-fundamentos-programacion/06-usuario-y-publico-objetivo' },
                    { label: '07 · Validar la idea', link: '/apuntes-pi1/u1-fundamentos-programacion/07-validar-la-idea' },
                    { label: '08 · El acta de definición', link: '/apuntes-pi1/u1-fundamentos-programacion/08-el-acta-de-definicion' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u1-fundamentos-programacion/09-cierre' },
                  ],
                },
                { label: '🏗️ U2. Diseñar la solución', link: '/apuntes-pi1/u2-poo' },
                { label: '🗄️ U3. Organizar los datos', link: '/apuntes-pi1/u3-diseno-bd' },
                {
                  label: '📄 U4. Documentar y comunicar',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u4-lenguajes-marcas' },
                    { label: '01 · Documentar no es opcional', link: '/apuntes-pi1/u4-lenguajes-marcas/01-documentar-no-es-opcional' },
                    { label: '02 · Qué documentar en PI1', link: '/apuntes-pi1/u4-lenguajes-marcas/02-que-documentar-en-pi1' },
                    { label: '03 · La estructura de la memoria', link: '/apuntes-pi1/u4-lenguajes-marcas/03-la-estructura-de-la-memoria' },
                    { label: '04 · Reglas de oro de la memoria', link: '/apuntes-pi1/u4-lenguajes-marcas/04-reglas-de-oro-de-la-memoria' },
                    { label: '05 · Presentaciones que no aburren', link: '/apuntes-pi1/u4-lenguajes-marcas/05-presentaciones-que-no-aburren' },
                    { label: '06 · La estructura de 10 minutos', link: '/apuntes-pi1/u4-lenguajes-marcas/06-la-estructura-de-10-minutos' },
                    { label: '07 · Lo que NO hacer en una defensa', link: '/apuntes-pi1/u4-lenguajes-marcas/07-lo-que-no-hacer-en-una-defensa' },
                    { label: '08 · Ensayo y plan B', link: '/apuntes-pi1/u4-lenguajes-marcas/08-ensayo-y-plan-b' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u4-lenguajes-marcas/09-cierre' },
                  ],
                },
                {
                  label: '🎨 U5. Construir la interfaz',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u5-frontend-basico' },
                    { label: '01 · La interfaz importa', link: '/apuntes-pi1/u5-frontend-basico/01-la-interfaz-importa' },
                    { label: '02 · Piensa en el usuario', link: '/apuntes-pi1/u5-frontend-basico/02-piensa-en-el-usuario' },
                    { label: '03 · Prototipo baja fidelidad', link: '/apuntes-pi1/u5-frontend-basico/03-prototipo-baja-fidelidad' },
                    { label: '04 · Prototipo interactivo', link: '/apuntes-pi1/u5-frontend-basico/04-prototipo-interactivo' },
                    { label: '05 · Implementación mobile-first', link: '/apuntes-pi1/u5-frontend-basico/05-implementacion-mobile-first' },
                    { label: '06 · Consistencia visual', link: '/apuntes-pi1/u5-frontend-basico/06-consistencia-visual' },
                    { label: '07 · Feedback y errores', link: '/apuntes-pi1/u5-frontend-basico/07-feedback-y-errores-visibles' },
                    { label: '08 · Lo que el tribunal mira', link: '/apuntes-pi1/u5-frontend-basico/08-lo-que-el-tribunal-mira' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u5-frontend-basico/09-cierre' },
                  ],
                },
                {
                  label: '⚙️ U6. Implementar la lógica',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u6-backend-basico' },
                    { label: '01 · El arte de empezar', link: '/apuntes-pi1/u6-backend-basico/01-el-arte-de-empezar' },
                    { label: '02 · Esqueleto incremental', link: '/apuntes-pi1/u6-backend-basico/02-esqueleto-incremental' },
                    { label: '03 · Estructura de carpetas', link: '/apuntes-pi1/u6-backend-basico/03-estructura-de-carpetas' },
                    { label: '04 · Comentarios que ayudan', link: '/apuntes-pi1/u6-backend-basico/04-comentarios-que-ayudan' },
                    { label: '05 · Refactorizar desde el principio', link: '/apuntes-pi1/u6-backend-basico/05-refactorizar-desde-el-principio' },
                    { label: '06 · Manejo de atascos', link: '/apuntes-pi1/u6-backend-basico/06-manejo-de-atascos' },
                    { label: '07 · Priorizar lo crítico', link: '/apuntes-pi1/u6-backend-basico/07-priorizar-lo-critico' },
                    { label: '08 · Checklist implementación', link: '/apuntes-pi1/u6-backend-basico/08-checklist-implementacion' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u6-backend-basico/09-cierre' },
                  ],
                },
                {
                  label: '👥 U7. Trabajar en equipo',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u7-git' },
                    { label: '01 · Equipo antes que código', link: '/apuntes-pi1/u7-git/01-el-equipo-antes-que-el-codigo' },
                    { label: '02 · Herramientas y reuniones', link: '/apuntes-pi1/u7-git/02-herramientas-y-reuniones' },
                    { label: '03 · Reparto de tareas', link: '/apuntes-pi1/u7-git/03-reparto-de-tareas' },
                    { label: '04 · Flujo Git main/dev/feature', link: '/apuntes-pi1/u7-git/04-flujo-git-main-dev-feature' },
                    { label: '05 · Código limpio en equipo', link: '/apuntes-pi1/u7-git/05-codigo-limpio-en-equipo' },
                    { label: '06 · Commits que se entienden', link: '/apuntes-pi1/u7-git/06-commits-que-se-entienden' },
                    { label: '07 · Code review', link: '/apuntes-pi1/u7-git/07-code-review' },
                    { label: '08 · Conflictos código y personas', link: '/apuntes-pi1/u7-git/08-conflictos-codigo-y-personas' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u7-git/09-cierre' },
                  ],
                },
                {
                  label: '📋 U8. Planificar y organizarse',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u8-metodologias' },
                    { label: '01 · Por qué planificar', link: '/apuntes-pi1/u8-metodologias/01-por-que-planificar-aunque-te-de-pereza' },
                    { label: '02 · Kanban el más visual', link: '/apuntes-pi1/u8-metodologias/02-kanban-el-mas-visual' },
                    { label: '03 · SCRUM sin burocracia', link: '/apuntes-pi1/u8-metodologias/03-scrum-sin-burocracia' },
                    { label: '04 · Cómo estimar bien', link: '/apuntes-pi1/u8-metodologias/04-como-estimar-bien' },
                    { label: '05 · Priorizar lo que importa', link: '/apuntes-pi1/u8-metodologias/05-priorizar-lo-que-importa' },
                    { label: '06 · Cómo recuperar el tiempo', link: '/apuntes-pi1/u8-metodologias/06-como-recuperar-el-tiempo' },
                    { label: '07 · Herramientas de seguimiento', link: '/apuntes-pi1/u8-metodologias/07-herramientas-de-seguimiento' },
                    { label: '08 · Checklist de planificación', link: '/apuntes-pi1/u8-metodologias/08-checklist-de-planificacion' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u8-metodologias/09-cierre' },
                  ],
                },
              ],
            },
            {
              label: '📗 PI2 - Cómo evolucionar el proyecto',
              collapsed: true,
              items: [
                { label: '🚪 Introducción', link: '/apuntes-pi2/' },
                {
                  label: '🔧 U1. Evolucionar la arquitectura',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u1-arquitectura-web' },
                    { label: '01 · El legado de PI1', link: '/apuntes-pi2/u1-arquitectura-web/01-el-legado-de-pi1' },
                    { label: '02 · Refactorizar sin romper', link: '/apuntes-pi2/u1-arquitectura-web/02-refactorizar-sin-romper' },
                    { label: '03 · Decisiones técnicas', link: '/apuntes-pi2/u1-arquitectura-web/03-decisiones-tecnicas-en-pi2' },
                    { label: '04 · Estructura de carpetas', link: '/apuntes-pi2/u1-arquitectura-web/04-estructura-de-carpetas-modular' },
                    { label: '05 · Versionado y ramas', link: '/apuntes-pi2/u1-arquitectura-web/05-versionado-y-ramas' },
                    { label: '06 · Documentar la arquitectura', link: '/apuntes-pi2/u1-arquitectura-web/06-documentar-la-arquitectura' },
                    { label: '07 · Deuda técnica en acción', link: '/apuntes-pi2/u1-arquitectura-web/07-deuda-tecnica-en-accion' },
                    { label: '08 · Checklist de arquitectura', link: '/apuntes-pi2/u1-arquitectura-web/08-checklist-de-arquitectura' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u1-arquitectura-web/09-cierre' },
                  ],
                },
                {
                  label: '🖥️ U2. Mejorar el frontend',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u2-frontend-framework' },
                    { label: '01 · Cuándo necesitas un framework', link: '/apuntes-pi2/u2-frontend-framework/01-cuando-necesitas-un-framework' },
                    { label: '02 · Elegir el framework adecuado', link: '/apuntes-pi2/u2-frontend-framework/02-elegir-el-framework-adecido' },
                    { label: '03 · Componentes: la pieza fundamental', link: '/apuntes-pi2/u2-frontend-framework/03-componentes-la-pieza-fundamental' },
                    { label: '04 · Gestionar el estado', link: '/apuntes-pi2/u2-frontend-framework/04-gestionar-el-estado' },
                    { label: '05 · Rendimiento y optimización', link: '/apuntes-pi2/u2-frontend-framework/05-rendimiento-y-optimizacion' },
                    { label: '06 · Accesibilidad web', link: '/apuntes-pi2/u2-frontend-framework/06-accesibilidad-web' },
                    { label: '07 · Probar la interfaz', link: '/apuntes-pi2/u2-frontend-framework/07-probar-la-interfaz' },
                    { label: '08 · Checklist de frontend', link: '/apuntes-pi2/u2-frontend-framework/08-checklist-de-frontend' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u2-frontend-framework/09-cierre' },
                  ],
                },
                {
                  label: '🔗 U3. Integrar sistemas',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u3-apis-rest' },
                    { label: '01 · Comunicación entre partes', link: '/apuntes-pi2/u3-apis-rest/01-comunicacion-entre-partes' },
                    { label: '02 · Definir la API', link: '/apuntes-pi2/u3-apis-rest/02-definir-la-api' },
                    { label: '03 · Contrato antes de codificar', link: '/apuntes-pi2/u3-apis-rest/03-contrato-antes-de-codificar' },
                    { label: '04 · Manejo de errores', link: '/apuntes-pi2/u3-apis-rest/04-manejo-de-errores' },
                    { label: '05 · Servicios externos', link: '/apuntes-pi2/u3-apis-rest/05-integrar-servicios-externos' },
                    { label: '06 · Seguridad en la comunicación', link: '/apuntes-pi2/u3-apis-rest/06-seguridad-en-la-comunicacion' },
                    { label: '07 · Herramientas de desarrollo', link: '/apuntes-pi2/u3-apis-rest/07-herramientas-de-desarrollo' },
                    { label: '08 · Checklist de integraciones', link: '/apuntes-pi2/u3-apis-rest/08-checklist-de-integraciones' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u3-apis-rest/09-cierre' },
                  ],
                },
                {
                  label: '👤 U4. Diseñar para el usuario',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u4-ui-ux' },
                    { label: '01 · UX no es "hacerlo bonito"', link: '/apuntes-pi2/u4-ui-ux/01-ux-no-es-hacerlo-bonito' },
                    { label: '02 · Principios de usabilidad', link: '/apuntes-pi2/u4-ui-ux/02-principios-de-usabilidad' },
                    { label: '03 · Accesibilidad para todos', link: '/apuntes-pi2/u4-ui-ux/03-accesibilidad-para-todos' },
                    { label: '04 · Diseño para móvil', link: '/apuntes-pi2/u4-ui-ux/04-diseno-para-movil' },
                    { label: '05 · Testing con usuarios', link: '/apuntes-pi2/u4-ui-ux/05-testing-con-usuarios' },
                    { label: '06 · Prototipado rápido', link: '/apuntes-pi2/u4-ui-ux/06-prototipado-rapido' },
                    { label: '07 · Microcopy y mensajes', link: '/apuntes-pi2/u4-ui-ux/07-microcopy-y-mensajes' },
                    { label: '08 · Checklist de usabilidad', link: '/apuntes-pi2/u4-ui-ux/08-checklist-de-usabilidad' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u4-ui-ux/09-cierre' },
                  ],
                },
                { label: '✅ U5. Asegurar la calidad', link: '/apuntes-pi2/u5-testing' },
                { label: '🛡️ U6. Proteger la aplicación', link: '/apuntes-pi2/u6-seguridad' },
                { label: '📦 U7. Preparar el despliegue', link: '/apuntes-pi2/u7-docker' },
                { label: '🚀 U8. Publicar y mantener', link: '/apuntes-pi2/u8-despliegue-ci-cd' },
                { label: '🔁 U9. Gestionar el proyecto', link: '/apuntes-pi2/u9-metodologias-agiles' },
              ],
            },
          ],
        },
      ],
    }),
    mdx(),
  ],
});
