import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mdx from '@astrojs/mdx';

export default defineConfig({
  site: 'https://sergarb1.github.io',
  base: '/ApuntesProyectoDAW',
  integrations: [
    starlight({
      title: 'Apuntes Proyecto Intermodular',
      description: 'Material didáctico de Proyecto Intermodular I y II - Desarrollo de Aplicaciones Web (DAW) · Curso 2026-2027',
      logo: {
        src: './src/assets/logo.svg',
        replacesTitle: false,
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/sergarb1/ApuntesProyectoDAW' },
      ],
      editLink: {
        baseUrl: 'https://github.com/sergarb1/ApuntesProyectoDAW/edit/main',
      },
      lastUpdated: true,
      pagination: true,
      pagefind: true,
      tableOfContents: {
        minHeadingLevel: 2,
        maxHeadingLevel: 4,
      },
      customCss: [
        './src/styles/custom.css',
      ],
      head: [
        {
          tag: 'link',
          attrs: {
            rel: 'icon',
            type: 'image/svg+xml',
            href: '/ApuntesProyectoDAW/favicon.svg',
          },
        },
        {
          tag: 'meta',
          attrs: {
            name: 'license',
            content: 'CC BY-SA 4.0',
          },
        },
      ],
      components: {
        Footer: './src/components/Footer.astro',
        Hero: './src/components/Hero.astro',
      },
      sidebar: [
        {
          label: '🏠 Inicio',
          link: '/',
        },
        {
          label: '📚 Material didáctico',
          collapsed: false,
          items: [
            {
              label: '🎯 Proyecto 1 — Bases y Planificación',
              collapsed: false,
              items: [
                { label: '📌 Introducción', link: '/guia-didactica/proyecto-1/' },
                { label: '🎓 Competencias', link: '/guia-didactica/proyecto-1/competencias' },
                {
                  label: '📋 Unidades Didácticas',
                  collapsed: false,
                  items: [
                    {
                      label: '🔍 UD 1.1: MVP',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp' },
                        { label: '01 · Qué es un MVP', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/01-que-es-un-mvp' },
                        { label: '02 · Identificar el problema', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/02-identificar-problema' },
                        { label: '03 · Definir features', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/03-definir-features' },
                        { label: '04 · Cortar sin piedad', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/04-cortar-sin-piedad' },
                        { label: '05 · Ejemplos reales', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/05-ejemplos-reales' },
                        { label: '06 · Errores comunes', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/06-errores-comunes' },
                        { label: '07 · Herramientas', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/07-herramientas' },
                        { label: '08 · Template MVP', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/08-template-mvp' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/09-cierre' },
                      ],
                    },
                    {
                      label: '📋 UD 1.2: SCRUM Lite',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite' },
                        { label: '01 · Qué es Ágil', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/01-que-es-agil' },
                        { label: '02 · Qué es SCRUM', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/02-que-es-scrum' },
                        { label: '03 · Sprint', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/03-sprint' },
                        { label: '04 · Kanban', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/04-kanban' },
                        { label: '05 · User Stories', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/05-user-stories' },
                        { label: '06 · Estimación', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/06-estimacion' },
                        { label: '07 · Errores SCRUM', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/07-errores-scrum' },
                        { label: '08 · Template Sprint', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/08-template-sprint' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/09-cierre' },
                      ],
                    },
                    {
                      label: '📝 UD 1.3: Requisitos',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos' },
                        { label: '01 · Qué son los requisitos', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/01-que-son-requisitos' },
                        { label: '02 · Requisitos funcionales', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/02-requisitos-funcionales' },
                        { label: '03 · Requisitos no funcionales', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/03-requisitos-no-funcionales' },
                        { label: '04 · Historias de usuario', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/04-historias-de-usuario' },
                        { label: '05 · Criterios de aceptación', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/05-criterios-aceptacion' },
                        { label: '06 · Priorización', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/06-priorizacion' },
                        { label: '07 · Errores de requisitos', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/07-errores-requisitos' },
                        { label: '08 · Template requisitos', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/08-template-requisitos' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/09-cierre' },
                      ],
                    },
                    {
                      label: '🛠️ UD 1.4: Tecnologías',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias' },
                        { label: '01 · Por qué elegir', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/01-por-que-elegir' },
                        { label: '02 · Criterios de elección', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/02-criterios-eleccion' },
                        { label: '03 · Lenguajes y frameworks', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/03-lenguajes-frameworks' },
                        { label: '04 · Bases de datos', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/04-bases-datos' },
                        { label: '05 · Frontend y Backend', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/05-frontend-backend' },
                        { label: '06 · Comparativa de stacks', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/06-comparativa-stack' },
                        { label: '07 · Justificación técnica', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/07-justificacion' },
                        { label: '08 · Template stack', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/08-template-stack' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/09-cierre' },
                      ],
                    },
                    {
                      label: '🗣️ UD 1.5: Comunicación',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion' },
                        { label: '01 · Por qué comunicar', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/01-por-que-comunicar' },
                        { label: '02 · Pitch de 5 minutos', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/02-pitch-5-minutos' },
                        { label: '03 · Lenguaje verbal', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/03-lenguaje-verbal' },
                        { label: '04 · Lenguaje no verbal', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/04-lenguaje-no-verbal' },
                        { label: '05 · Memoria del proyecto', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/05-memoria' },
                        { label: '06 · Diapositivas', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/06-diapositivas' },
                        { label: '07 · Demo práctica', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/07-demo-practica' },
                        { label: '08 · Preguntas del tribunal', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/08-preguntas-tribunal' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/09-cierre' },
                      ],
                    },
                    {
                      label: '📚 UD 1.6: Documentación',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion' },
                        { label: '01 · Por qué documentar', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/01-por-que-documentar' },
                        { label: '02 · README', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/02-readme' },
                        { label: '03 · Doc técnica', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/03-doc-tecnica' },
                        { label: '04 · Manual de usuario', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/04-manual-usuario' },
                        { label: '05 · Markdown', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/05-markdown' },
                        { label: '06 · Herramientas de doc', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/06-herramientas-doc' },
                        { label: '07 · Errores de doc', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/07-errores-doc' },
                        { label: '08 · Template doc', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/08-template-doc' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/09-cierre' },
                      ],
                    },
                    {
                      label: '🎯 UD 1.7: Propuesta',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta' },
                        { label: '01 · Qué es una propuesta', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/01-que-es-propuesta' },
                        { label: '02 · Briefing', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/02-briefing' },
                        { label: '03 · Ideas de proyecto', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/03-ideas-proyecto' },
                        { label: '04 · Selección de idea', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/04-seleccion-idea' },
                        { label: '05 · Definición de alcance', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/05-definicion-alcance' },
                        { label: '06 · Cronograma', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/06-cronograma' },
                        { label: '07 · Ejemplo de propuesta', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/07-ejemplo-propuesta' },
                        { label: '08 · Errores de propuesta', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/08-errores-propuesta' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/09-cierre' },
                      ],
                    },
                  ],
                },
                { label: '✅ Evaluación', link: '/guia-didactica/proyecto-1/evaluacion' },
              ],
            },
            {
              label: '🚀 Proyecto 2 — Desarrollo Avanzado',
              collapsed: false,
              items: [
                { label: '📌 Introducción', link: '/guia-didactica/proyecto-2/' },
                { label: '🎓 Competencias', link: '/guia-didactica/proyecto-2/competencias' },
                {
                  label: '📋 Unidades Didácticas',
                  collapsed: false,
                  items: [
                    {
                      label: '📋 UD 2.1: Requisitos Avanzado',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado' },
                        { label: '01 · INVEST', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/01-invest' },
                        { label: '02 · MoSCoW avanzado', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/02-moscow-avanzado' },
                        { label: '03 · Estimación por puntos', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/03-estimacion-puntos' },
                        { label: '04 · Refinamiento del backlog', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/04-refinamiento-backlog' },
                        { label: '05 · Criterios avanzados', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/05-criterios-aceptacion-avanzado' },
                        { label: '06 · Trazabilidad', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/06-trazabilidad' },
                        { label: '07 · Errores avanzados', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/07-errores-requisitos-avanzado' },
                        { label: '08 · Template avanzado', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/08-template-requisitos-avanzado' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/09-cierre' },
                      ],
                    },
                    {
                      label: '🔄 UD 2.2: SCRUM Avanzado',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado' },
                        { label: '01 · Planning Poker', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/01-planning-poker' },
                        { label: '02 · Velocity', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/02-velocity' },
                        { label: '03 · Burndown y Burnup', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/03-burndown-burnup' },
                        { label: '04 · Bloqueos y dependencias', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/04-bloqueos-dependencias' },
                        { label: '05 · Retrospectivas avanzadas', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/05-retrospectivas-avanzadas' },
                        { label: '06 · Métricas SCRUM', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/06-metricas-scrum' },
                        { label: '07 · SCRUM Master estudiante', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/07-scrum-master-estudiante' },
                        { label: '08 · Template SCRUM', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/08-template-scrum-avanzado' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/09-cierre' },
                      ],
                    },
                    {
                      label: '🌿 UD 2.3: Git Avanzado',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado' },
                        { label: '01 · GitFlow', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/01-gitflow' },
                        { label: '02 · Trunk-Based', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/02-trunk-based' },
                        { label: '03 · Conflictos', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/03-conflictos' },
                        { label: '04 · Hooks', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/04-hooks' },
                        { label: '05 · CI/CD', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/05-ci-cd' },
                        { label: '06 · Convenciones de commits', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/06-convenciones-commits' },
                        { label: '07 · Code Review', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/07-code-review' },
                        { label: '08 · Template Git', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/08-template-git' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/09-cierre' },
                      ],
                    },
                    {
                      label: '🧪 UD 2.4: Testing',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-4-testing' },
                        { label: '01 · Por qué hacer tests', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/01-por-que-hacer-tests' },
                        { label: '02 · Tipos de test', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/02-tipos-de-test' },
                        { label: '03 · Qué probar', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/03-que-probar' },
                        { label: '04 · Tests en el flujo', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/04-tests-en-el-flujo' },
                        { label: '05 · Pruebas manuales', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/05-pruebas-manuales' },
                        { label: '06 · Herramientas', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/06-herramientas' },
                        { label: '07 · Testing en equipo', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/07-testing-en-equipo' },
                        { label: '08 · Checklist de calidad', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/08-checklist-calidad' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-4-testing/09-cierre' },
                      ],
                    },
                    {
                      label: '🏗️ UD 2.5: Patrones de Diseño',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno' },
                        { label: '01 · Qué son los patrones', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/01-que-son-patrones' },
                        { label: '02 · Creacionales', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/02-creacionales' },
                        { label: '03 · Estructurales', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/03-estructurales' },
                        { label: '04 · Comportamiento', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/04-comportamiento' },
                        { label: '05 · MVC', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/05-mvc' },
                        { label: '06 · Repository', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/06-repository' },
                        { label: '07 · Cuándo usar', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/07-cuando-usar' },
                        { label: '08 · Template patrones', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/08-template-patrones' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-5-patrones-diseno/09-cierre' },
                      ],
                    },
                    {
                      label: '📐 UD 2.6: Diagramas',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas' },
                        { label: '01 · Qué son los diagramas', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/01-que-son-diagramas' },
                        { label: '02 · Modelo C4', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/02-c4-model' },
                        { label: '03 · Diagrama ER', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/03-diagrama-er' },
                        { label: '04 · Diagrama de secuencia', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/04-diagrama-secuencia' },
                        { label: '05 · Símbolos UML', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/05-simbolos-uml' },
                        { label: '06 · Mermaid', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/06-mermaid' },
                        { label: '07 · Herramientas', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/07-herramientas-diagramas' },
                        { label: '08 · Template diagramas', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/08-template-diagramas' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-6-diagramas/09-cierre' },
                      ],
                    },
                    {
                      label: '🤖 UD 2.7: IA como Copiloto',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto' },
                        { label: '01 · Qué hace bien y mal', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/01-que-hace-bien-mal' },
                        { label: '02 · Prompts efectivos', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/02-prompts-efectivos' },
                        { label: '03 · Asistentes de IA', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/03-asistentes-ia' },
                        { label: '04 · Agentes', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/04-agentes' },
                        { label: '05 · Skills', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/05-skills' },
                        { label: '06 · opencode', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/06-opencode' },
                        { label: '07 · Spec-Driven Dev', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/07-spec-driven-openspec' },
                        { label: '08 · Testing de IA', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/08-testing-ia' },
                        { label: '09 · Seguridad con IA', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/09-seguridad-ia' },
                        { label: '10 · Ética de la IA', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/10-etica-ia' },
                        { label: '11 · Errores de IA', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/11-errores-ia' },
                        { label: '12 · Template IA', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/12-template-ia' },
                        { label: '13 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-7-ia-copiloto/13-cierre' },
                      ],
                    },
                    {
                      label: '☁️ UD 2.8: Despliegue',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue' },
                        { label: '01 · Qué es el despliegue', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/01-que-es-despliegue' },
                        { label: '02 · Docker', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/02-docker' },
                        { label: '03 · CI/CD', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/03-ci-cd-despliegue' },
                        { label: '04 · Plataformas', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/04-plataformas' },
                        { label: '05 · Zero-downtime', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/05-zero-downtime' },
                        { label: '06 · Checklist despliegue', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/06-checklist-despliegue' },
                        { label: '07 · Errores de despliegue', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/07-errores-despliegue' },
                        { label: '08 · Template despliegue', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/08-template-despliegue' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-8-despliegue/09-cierre' },
                      ],
                    },
                    {
                      label: '📊 UD 2.9: Monitorización',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion' },
                        { label: '01 · Qué son los logs', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/01-que-son-logs' },
                        { label: '02 · Métricas', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/02-metricas' },
                        { label: '03 · Prometheus y Grafana', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/03-prometheus-grafana' },
                        { label: '04 · Alertas', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/04-alertas' },
                        { label: '05 · Stack mínimo', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/05-stack-minimo' },
                        { label: '06 · Configuración', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/06-configuracion' },
                        { label: '07 · Dashboards', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/07-dashboard' },
                        { label: '08 · Template monitorización', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/08-template-monitorizacion' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-9-monitorizacion/09-cierre' },
                      ],
                    },
                    {
                      label: '🚀 UD 2.10: Propuesta Final',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final' },
                        { label: '01 · Briefing final', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/01-briefing-final' },
                        { label: '02 · Ideas finales', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/02-ideas-finales' },
                        { label: '03 · Selección de idea', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/03-seleccion-idea-final' },
                        { label: '04 · Stack final', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/04-stack-final' },
                        { label: '05 · Features finales', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/05-features-finales' },
                        { label: '06 · Cronograma final', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/06-cronograma-final' },
                        { label: '07 · Entregables', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/07-entregables' },
                        { label: '08 · Evaluación', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/08-evaluacion' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-10-propuesta-final/09-cierre' },
                      ],
                    },
                  ],
                },
                { label: '📦 Entregables', link: '/guia-didactica/proyecto-2/entregables' },
                { label: '✅ Evaluación', link: '/guia-didactica/proyecto-2/evaluacion' },
              ],
            },
            { label: '⚙️ Metodología', link: '/metodologia' },
            { label: '🛠️ Herramientas', link: '/herramientas' },
            { label: '📖 Recursos', link: '/recursos' },
            { label: '⚖️ Licencia', link: '/licencia' },
            { label: '❓ Preguntas Frecuentes', link: '/faq' },
            { label: '💡 Ideas para Proyectos', link: '/ideas' },
          ],
        },
      ],
    }),
    mdx(),
  ],
});
