import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mdx from '@astrojs/mdx';

export default defineConfig({
  site: 'https://sergarb1.github.io',
  base: '/ApuntesProyectoDAW',
  integrations: [
    starlight({
      title: 'Apuntes Proyecto Intermodular',
      description: 'Guía Didáctica de Proyecto Intermodular I y II - Desarrollo de Aplicaciones Web (DAW) · Curso 2026-2027',
      logo: {
        src: './src/assets/logo.svg',
        replacesTitle: false,
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/sergarb1/ApuntesProyectoDAW' },
      ],
      editLink: {
        baseUrl: 'https://github.com/sergarb1/ApuntesProyectoDAW/edit/main',
      },
      lastUpdated: true,
      pagination: true,
      pagefind: true,
      tableOfContents: {
        minHeadingLevel: 2,
        maxHeadingLevel: 4,
      },
      customCss: [
        './src/styles/custom.css',
      ],
      head: [
        {
          tag: 'link',
          attrs: {
            rel: 'icon',
            type: 'image/svg+xml',
            href: '/ApuntesProyectoDAW/favicon.svg',
          },
        },
        {
          tag: 'meta',
          attrs: {
            name: 'license',
            content: 'CC BY-SA 4.0',
          },
        },
      ],
      components: {
        Footer: './src/components/Footer.astro',
        Hero: './src/components/Hero.astro',
      },
      sidebar: [
        {
          label: '🏠 Inicio',
          link: '/',
        },
        {
          label: '📚 Guía Didáctica',
          collapsed: false,
          items: [
            { label: '🔄 Continuidad PI1 → PI2', link: '/continuidad' },
            {
              label: '🎯 Proyecto 1 — Bases y Planificación',
              collapsed: false,
              items: [
                { label: '📌 Introducción', link: '/guia-didactica/proyecto-1/' },
                { label: '🎓 Competencias', link: '/guia-didactica/proyecto-1/competencias' },
                {
                  label: '📋 Unidades Didácticas',
                  collapsed: false,
                  items: [
                    {
                      label: '🔍 UD 1.1: MVP',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp' },
                        { label: '01 · Qué es un MVP', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/01-que-es-un-mvp' },
                        { label: '02 · Identificar el problema', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/02-identificar-problema' },
                        { label: '03 · Definir features', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/03-definir-features' },
                        { label: '04 · Cortar sin piedad', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/04-cortar-sin-piedad' },
                        { label: '05 · Ejemplos reales', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/05-ejemplos-reales' },
                        { label: '06 · Errores comunes', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/06-errores-comunes' },
                        { label: '07 · Herramientas', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/07-herramientas' },
                        { label: '08 · Template MVP', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/08-template-mvp' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-1-mvp/09-cierre' },
                      ],
                    },
                    {
                      label: '📋 UD 1.2: SCRUM Lite',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite' },
                        { label: '01 · Qué es Ágil', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/01-que-es-agil' },
                        { label: '02 · Qué es SCRUM', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/02-que-es-scrum' },
                        { label: '03 · Sprint', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/03-sprint' },
                        { label: '04 · Kanban', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/04-kanban' },
                        { label: '05 · User Stories', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/05-user-stories' },
                        { label: '06 · Estimación', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/06-estimacion' },
                        { label: '07 · Errores SCRUM', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/07-errores-scrum' },
                        { label: '08 · Template Sprint', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/08-template-sprint' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-2-scrum-lite/09-cierre' },
                      ],
                    },
                    {
                      label: '📝 UD 1.3: Requisitos',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos' },
                        { label: '01 · Qué son los requisitos', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/01-que-son-requisitos' },
                        { label: '02 · Requisitos funcionales', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/02-requisitos-funcionales' },
                        { label: '03 · Requisitos no funcionales', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/03-requisitos-no-funcionales' },
                        { label: '04 · Historias de usuario', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/04-historias-de-usuario' },
                        { label: '05 · Criterios de aceptación', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/05-criterios-aceptacion' },
                        { label: '06 · Priorización', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/06-priorizacion' },
                        { label: '07 · Errores de requisitos', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/07-errores-requisitos' },
                        { label: '08 · Template requisitos', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/08-template-requisitos' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-3-requisitos/09-cierre' },
                      ],
                    },
                    {
                      label: '🛠️ UD 1.4: Tecnologías',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias' },
                        { label: '01 · Por qué elegir', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/01-por-que-elegir' },
                        { label: '02 · Criterios de elección', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/02-criterios-eleccion' },
                        { label: '03 · Lenguajes y frameworks', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/03-lenguajes-frameworks' },
                        { label: '04 · Bases de datos', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/04-bases-datos' },
                        { label: '05 · Frontend y Backend', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/05-frontend-backend' },
                        { label: '06 · Comparativa de stacks', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/06-comparativa-stack' },
                        { label: '07 · Justificación técnica', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/07-justificacion' },
                        { label: '08 · Template stack', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/08-template-stack' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-4-eleccion-tecnologias/09-cierre' },
                      ],
                    },
                    {
                      label: '🗣️ UD 1.5: Comunicación',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion' },
                        { label: '01 · Por qué comunicar', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/01-por-que-comunicar' },
                        { label: '02 · Pitch de 5 minutos', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/02-pitch-5-minutos' },
                        { label: '03 · Lenguaje verbal', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/03-lenguaje-verbal' },
                        { label: '04 · Lenguaje no verbal', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/04-lenguaje-no-verbal' },
                        { label: '05 · Memoria del proyecto', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/05-memoria' },
                        { label: '06 · Diapositivas', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/06-diapositivas' },
                        { label: '07 · Demo práctica', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/07-demo-practica' },
                        { label: '08 · Preguntas del tribunal', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/08-preguntas-tribunal' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-5-comunicacion/09-cierre' },
                      ],
                    },
                    {
                      label: '📚 UD 1.6: Documentación',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion' },
                        { label: '01 · Por qué documentar', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/01-por-que-documentar' },
                        { label: '02 · README', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/02-readme' },
                        { label: '03 · Doc técnica', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/03-doc-tecnica' },
                        { label: '04 · Manual de usuario', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/04-manual-usuario' },
                        { label: '05 · Markdown', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/05-markdown' },
                        { label: '06 · Herramientas de doc', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/06-herramientas-doc' },
                        { label: '07 · Errores de doc', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/07-errores-doc' },
                        { label: '08 · Template doc', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/08-template-doc' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-6-documentacion/09-cierre' },
                      ],
                    },
                    {
                      label: '🎯 UD 1.7: Propuesta',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta' },
                        { label: '01 · Qué es una propuesta', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/01-que-es-propuesta' },
                        { label: '02 · Briefing', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/02-briefing' },
                        { label: '03 · Ideas de proyecto', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/03-ideas-proyecto' },
                        { label: '04 · Selección de idea', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/04-seleccion-idea' },
                        { label: '05 · Definición de alcance', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/05-definicion-alcance' },
                        { label: '06 · Cronograma', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/06-cronograma' },
                        { label: '07 · Ejemplo de propuesta', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/07-ejemplo-propuesta' },
                        { label: '08 · Errores de propuesta', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/08-errores-propuesta' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-1/uds/u1-7-propuesta/09-cierre' },
                      ],
                    },
                  ],
                },
                { label: '✅ Evaluación', link: '/guia-didactica/proyecto-1/evaluacion' },
              ],
            },
            {
              label: '🚀 Proyecto 2 — Desarrollo Avanzado',
              collapsed: false,
              items: [
                { label: '📌 Introducción', link: '/guia-didactica/proyecto-2/' },
                { label: '🎓 Competencias', link: '/guia-didactica/proyecto-2/competencias' },
                {
                  label: '📋 Unidades Didácticas',
                  collapsed: false,
                  items: [
                    {
                      label: '📋 UD 2.1: Requisitos Avanzado',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado' },
                        { label: '01 · INVEST', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/01-invest' },
                        { label: '02 · MoSCoW avanzado', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/02-moscow-avanzado' },
                        { label: '03 · Estimación por puntos', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/03-estimacion-puntos' },
                        { label: '04 · Refinamiento del backlog', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/04-refinamiento-backlog' },
                        { label: '05 · Criterios avanzados', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/05-criterios-aceptacion-avanzado' },
                        { label: '06 · Trazabilidad', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/06-trazabilidad' },
                        { label: '07 · Errores avanzados', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/07-errores-requisitos-avanzado' },
                        { label: '08 · Template avanzado', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/08-template-requisitos-avanzado' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-1-requisitos-avanzado/09-cierre' },
                      ],
                    },
                    {
                      label: '🔄 UD 2.2: SCRUM Avanzado',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado' },
                        { label: '01 · Planning Poker', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/01-planning-poker' },
                        { label: '02 · Velocity', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/02-velocity' },
                        { label: '03 · Burndown y Burnup', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/03-burndown-burnup' },
                        { label: '04 · Bloqueos y dependencias', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/04-bloqueos-dependencias' },
                        { label: '05 · Retrospectivas avanzadas', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/05-retrospectivas-avanzadas' },
                        { label: '06 · Métricas SCRUM', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/06-metricas-scrum' },
                        { label: '07 · SCRUM Master estudiante', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/07-scrum-master-estudiante' },
                        { label: '08 · Template SCRUM', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/08-template-scrum-avanzado' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-2-scrum-avanzado/09-cierre' },
                      ],
                    },
                    {
                      label: '🌿 UD 2.3: Git Avanzado',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado' },
                        { label: '01 · GitFlow', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/01-gitflow' },
                        { label: '02 · Trunk-Based', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/02-trunk-based' },
                        { label: '03 · Conflictos', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/03-conflictos' },
                        { label: '04 · Hooks', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/04-hooks' },
                        { label: '05 · CI/CD', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/05-ci-cd' },
                        { label: '06 · Convenciones de commits', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/06-convenciones-commits' },
                        { label: '07 · Code Review', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/07-code-review' },
                        { label: '08 · Template Git', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/08-template-git' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-3-git-avanzado/09-cierre' },
                      ],
                    },
                    {
                      label: '🏗️ UD 2.4: Patrones de Diseño',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno' },
                        { label: '01 · Qué son los patrones', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/01-que-son-patrones' },
                        { label: '02 · Creacionales', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/02-creacionales' },
                        { label: '03 · Estructurales', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/03-estructurales' },
                        { label: '04 · Comportamiento', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/04-comportamiento' },
                        { label: '05 · MVC', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/05-mvc' },
                        { label: '06 · Repository', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/06-repository' },
                        { label: '07 · Cuándo usar', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/07-cuando-usar' },
                        { label: '08 · Template patrones', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/08-template-patrones' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-4-patrones-diseno/09-cierre' },
                      ],
                    },
                    {
                      label: '📐 UD 2.5: Diagramas',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas' },
                        { label: '01 · Qué son los diagramas', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/01-que-son-diagramas' },
                        { label: '02 · Modelo C4', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/02-c4-model' },
                        { label: '03 · Diagrama ER', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/03-diagrama-er' },
                        { label: '04 · Diagrama de secuencia', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/04-diagrama-secuencia' },
                        { label: '05 · Símbolos UML', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/05-simbolos-uml' },
                        { label: '06 · Mermaid', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/06-mermaid' },
                        { label: '07 · Herramientas', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/07-herramientas-diagramas' },
                        { label: '08 · Template diagramas', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/08-template-diagramas' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-5-diagramas/09-cierre' },
                      ],
                    },
                    {
                      label: '🤖 UD 2.6: IA como Copiloto',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto' },
                        { label: '01 · Qué hace bien y mal', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/01-que-hace-bien-mal' },
                        { label: '02 · Prompts efectivos', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/02-prompts-efectivos' },
                        { label: '03 · GitHub Copilot', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/03-copilot-github' },
                        { label: '04 · Testing de IA', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/04-testing-ia' },
                        { label: '05 · Seguridad con IA', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/05-seguridad-ia' },
                        { label: '06 · Ética de la IA', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/06-etica-ia' },
                        { label: '07 · Errores de IA', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/07-errores-ia' },
                        { label: '08 · Template IA', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/08-template-ia' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-6-ia-copiloto/09-cierre' },
                      ],
                    },
                    {
                      label: '☁️ UD 2.7: Despliegue',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue' },
                        { label: '01 · Qué es el despliegue', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/01-que-es-despliegue' },
                        { label: '02 · Docker', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/02-docker' },
                        { label: '03 · CI/CD', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/03-ci-cd-despliegue' },
                        { label: '04 · Plataformas', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/04-plataformas' },
                        { label: '05 · Zero-downtime', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/05-zero-downtime' },
                        { label: '06 · Checklist despliegue', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/06-checklist-despliegue' },
                        { label: '07 · Errores de despliegue', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/07-errores-despliegue' },
                        { label: '08 · Template despliegue', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/08-template-despliegue' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-7-despliegue/09-cierre' },
                      ],
                    },
                    {
                      label: '📊 UD 2.8: Monitorización',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion' },
                        { label: '01 · Qué son los logs', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/01-que-son-logs' },
                        { label: '02 · Métricas', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/02-metricas' },
                        { label: '03 · Prometheus y Grafana', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/03-prometheus-grafana' },
                        { label: '04 · Alertas', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/04-alertas' },
                        { label: '05 · Stack mínimo', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/05-stack-minimo' },
                        { label: '06 · Configuración', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/06-configuracion' },
                        { label: '07 · Dashboards', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/07-dashboard' },
                        { label: '08 · Template monitorización', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/08-template-monitorizacion' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-8-monitorizacion/09-cierre' },
                      ],
                    },
                    {
                      label: '🚀 UD 2.9: Propuesta Final',
                      collapsed: true,
                      items: [
                        { label: '📑 Índice', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final' },
                        { label: '01 · Briefing final', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/01-briefing-final' },
                        { label: '02 · Ideas finales', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/02-ideas-finales' },
                        { label: '03 · Selección de idea', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/03-seleccion-idea-final' },
                        { label: '04 · Stack final', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/04-stack-final' },
                        { label: '05 · Features finales', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/05-features-finales' },
                        { label: '06 · Cronograma final', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/06-cronograma-final' },
                        { label: '07 · Entregables', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/07-entregables' },
                        { label: '08 · Evaluación', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/08-evaluacion' },
                        { label: '09 · Cierre', link: '/guia-didactica/proyecto-2/uds/u2-9-propuesta-final/09-cierre' },
                      ],
                    },
                  ],
                },
                { label: '📦 Entregables', link: '/guia-didactica/proyecto-2/entregables' },
                { label: '✅ Evaluación', link: '/guia-didactica/proyecto-2/evaluacion' },
              ],
            },
            { label: '⚙️ Metodología', link: '/metodologia' },
            { label: '🛠️ Herramientas', link: '/herramientas' },
            { label: '📖 Recursos', link: '/recursos' },
            { label: '⚖️ Licencia', link: '/licencia' },
            { label: '❓ Preguntas Frecuentes', link: '/faq' },
            { label: '💡 Ideas para Proyectos', link: '/ideas' },
          ],
        },
        {
          label: '📝 Apuntes',
          collapsed: true,
          items: [
            {
              label: '📓 PI1 - Cómo afrontar el proyecto',
              collapsed: true,
              items: [
                { label: '🚪 Introducción', link: '/apuntes-pi1/' },
                { label: '🗺️ Ruta de aprendizaje', link: '/apuntes-pi1/ruta-aprendizaje' },
                {
                  label: '🧭 U1. Definir el proyecto',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u1-fundamentos-programacion' },
                    { label: '01 · De la idea al proyecto', link: '/apuntes-pi1/u1-fundamentos-programacion/01-de-la-idea-al-proyecto' },
                    { label: '02 · El MVP como mentalidad', link: '/apuntes-pi1/u1-fundamentos-programacion/02-el-mvp-como-mentalidad' },
                    { label: '03 · Las cinco preguntas', link: '/apuntes-pi1/u1-fundamentos-programacion/03-las-cinco-preguntas' },
                    { label: '04 · Objetivos SMART', link: '/apuntes-pi1/u1-fundamentos-programacion/04-objetivos-smart' },
                    { label: '05 · El alcance', link: '/apuntes-pi1/u1-fundamentos-programacion/05-el-alcance' },
                    { label: '06 · Usuario y público objetivo', link: '/apuntes-pi1/u1-fundamentos-programacion/06-usuario-y-publico-objetivo' },
                    { label: '07 · Validar la idea', link: '/apuntes-pi1/u1-fundamentos-programacion/07-validar-la-idea' },
                    { label: '08 · El acta de definición', link: '/apuntes-pi1/u1-fundamentos-programacion/08-el-acta-de-definicion' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u1-fundamentos-programacion/09-cierre' },
                  ],
                },
                { label: '🏗️ U2. Diseñar la solución', link: '/apuntes-pi1/u2-poo' },
                { label: '🗄️ U3. Organizar los datos', link: '/apuntes-pi1/u3-diseno-bd' },
                {
                  label: '📄 U4. Documentar y comunicar',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u4-lenguajes-marcas' },
                    { label: '01 · Documentar no es opcional', link: '/apuntes-pi1/u4-lenguajes-marcas/01-documentar-no-es-opcional' },
                    { label: '02 · Qué documentar en PI1', link: '/apuntes-pi1/u4-lenguajes-marcas/02-que-documentar-en-pi1' },
                    { label: '03 · La estructura de la memoria', link: '/apuntes-pi1/u4-lenguajes-marcas/03-la-estructura-de-la-memoria' },
                    { label: '04 · Reglas de oro de la memoria', link: '/apuntes-pi1/u4-lenguajes-marcas/04-reglas-de-oro-de-la-memoria' },
                    { label: '05 · Presentaciones que no aburren', link: '/apuntes-pi1/u4-lenguajes-marcas/05-presentaciones-que-no-aburren' },
                    { label: '06 · La estructura de 10 minutos', link: '/apuntes-pi1/u4-lenguajes-marcas/06-la-estructura-de-10-minutos' },
                    { label: '07 · Lo que NO hacer en una defensa', link: '/apuntes-pi1/u4-lenguajes-marcas/07-lo-que-no-hacer-en-una-defensa' },
                    { label: '08 · Ensayo y plan B', link: '/apuntes-pi1/u4-lenguajes-marcas/08-ensayo-y-plan-b' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u4-lenguajes-marcas/09-cierre' },
                  ],
                },
                {
                  label: '🎨 U5. Construir la interfaz',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u5-frontend-basico' },
                    { label: '01 · La interfaz importa', link: '/apuntes-pi1/u5-frontend-basico/01-la-interfaz-importa' },
                    { label: '02 · Piensa en el usuario', link: '/apuntes-pi1/u5-frontend-basico/02-piensa-en-el-usuario' },
                    { label: '03 · Prototipo baja fidelidad', link: '/apuntes-pi1/u5-frontend-basico/03-prototipo-baja-fidelidad' },
                    { label: '04 · Prototipo interactivo', link: '/apuntes-pi1/u5-frontend-basico/04-prototipo-interactivo' },
                    { label: '05 · Implementación mobile-first', link: '/apuntes-pi1/u5-frontend-basico/05-implementacion-mobile-first' },
                    { label: '06 · Consistencia visual', link: '/apuntes-pi1/u5-frontend-basico/06-consistencia-visual' },
                    { label: '07 · Feedback y errores', link: '/apuntes-pi1/u5-frontend-basico/07-feedback-y-errores-visibles' },
                    { label: '08 · Lo que el tribunal mira', link: '/apuntes-pi1/u5-frontend-basico/08-lo-que-el-tribunal-mira' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u5-frontend-basico/09-cierre' },
                  ],
                },
                {
                  label: '⚙️ U6. Implementar la lógica',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u6-backend-basico' },
                    { label: '01 · El arte de empezar', link: '/apuntes-pi1/u6-backend-basico/01-el-arte-de-empezar' },
                    { label: '02 · Esqueleto incremental', link: '/apuntes-pi1/u6-backend-basico/02-esqueleto-incremental' },
                    { label: '03 · Estructura de carpetas', link: '/apuntes-pi1/u6-backend-basico/03-estructura-de-carpetas' },
                    { label: '04 · Comentarios que ayudan', link: '/apuntes-pi1/u6-backend-basico/04-comentarios-que-ayudan' },
                    { label: '05 · Refactorizar desde el principio', link: '/apuntes-pi1/u6-backend-basico/05-refactorizar-desde-el-principio' },
                    { label: '06 · Manejo de atascos', link: '/apuntes-pi1/u6-backend-basico/06-manejo-de-atascos' },
                    { label: '07 · Priorizar lo crítico', link: '/apuntes-pi1/u6-backend-basico/07-priorizar-lo-critico' },
                    { label: '08 · Checklist implementación', link: '/apuntes-pi1/u6-backend-basico/08-checklist-implementacion' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u6-backend-basico/09-cierre' },
                  ],
                },
                {
                  label: '👥 U7. Trabajar en equipo',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u7-git' },
                    { label: '01 · Equipo antes que código', link: '/apuntes-pi1/u7-git/01-el-equipo-antes-que-el-codigo' },
                    { label: '02 · Herramientas y reuniones', link: '/apuntes-pi1/u7-git/02-herramientas-y-reuniones' },
                    { label: '03 · Reparto de tareas', link: '/apuntes-pi1/u7-git/03-reparto-de-tareas' },
                    { label: '04 · Flujo Git main/dev/feature', link: '/apuntes-pi1/u7-git/04-flujo-git-main-dev-feature' },
                    { label: '05 · Código limpio en equipo', link: '/apuntes-pi1/u7-git/05-codigo-limpio-en-equipo' },
                    { label: '06 · Commits que se entienden', link: '/apuntes-pi1/u7-git/06-commits-que-se-entienden' },
                    { label: '07 · Code review', link: '/apuntes-pi1/u7-git/07-code-review' },
                    { label: '08 · Conflictos código y personas', link: '/apuntes-pi1/u7-git/08-conflictos-codigo-y-personas' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u7-git/09-cierre' },
                  ],
                },
                {
                  label: '📋 U8. Planificar y organizarse',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi1/u8-metodologias' },
                    { label: '01 · Por qué planificar', link: '/apuntes-pi1/u8-metodologias/01-por-que-planificar-aunque-te-de-pereza' },
                    { label: '02 · Kanban el más visual', link: '/apuntes-pi1/u8-metodologias/02-kanban-el-mas-visual' },
                    { label: '03 · SCRUM sin burocracia', link: '/apuntes-pi1/u8-metodologias/03-scrum-sin-burocracia' },
                    { label: '04 · Cómo estimar bien', link: '/apuntes-pi1/u8-metodologias/04-como-estimar-bien' },
                    { label: '05 · Priorizar lo que importa', link: '/apuntes-pi1/u8-metodologias/05-priorizar-lo-que-importa' },
                    { label: '06 · Cómo recuperar el tiempo', link: '/apuntes-pi1/u8-metodologias/06-como-recuperar-el-tiempo' },
                    { label: '07 · Herramientas de seguimiento', link: '/apuntes-pi1/u8-metodologias/07-herramientas-de-seguimiento' },
                    { label: '08 · Checklist de planificación', link: '/apuntes-pi1/u8-metodologias/08-checklist-de-planificacion' },
                    { label: '09 · Cierre', link: '/apuntes-pi1/u8-metodologias/09-cierre' },
                  ],
                },
              ],
            },
            {
              label: '📗 PI2 - Cómo evolucionar el proyecto',
              collapsed: true,
              items: [
                { label: '🚪 Introducción', link: '/apuntes-pi2/' },
                {
                  label: '🔧 U1. Evolucionar la arquitectura',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u1-arquitectura-web' },
                    { label: '01 · El legado de PI1', link: '/apuntes-pi2/u1-arquitectura-web/01-el-legado-de-pi1' },
                    { label: '02 · Refactorizar sin romper', link: '/apuntes-pi2/u1-arquitectura-web/02-refactorizar-sin-romper' },
                    { label: '03 · Decisiones técnicas', link: '/apuntes-pi2/u1-arquitectura-web/03-decisiones-tecnicas-en-pi2' },
                    { label: '04 · Estructura de carpetas', link: '/apuntes-pi2/u1-arquitectura-web/04-estructura-de-carpetas-modular' },
                    { label: '05 · Versionado y ramas', link: '/apuntes-pi2/u1-arquitectura-web/05-versionado-y-ramas' },
                    { label: '06 · Documentar la arquitectura', link: '/apuntes-pi2/u1-arquitectura-web/06-documentar-la-arquitectura' },
                    { label: '07 · Deuda técnica en acción', link: '/apuntes-pi2/u1-arquitectura-web/07-deuda-tecnica-en-accion' },
                    { label: '08 · Checklist de arquitectura', link: '/apuntes-pi2/u1-arquitectura-web/08-checklist-de-arquitectura' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u1-arquitectura-web/09-cierre' },
                  ],
                },
                {
                  label: '🖥️ U2. Mejorar el frontend',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u2-frontend-framework' },
                    { label: '01 · Cuándo necesitas un framework', link: '/apuntes-pi2/u2-frontend-framework/01-cuando-necesitas-un-framework' },
                    { label: '02 · Elegir el framework adecuado', link: '/apuntes-pi2/u2-frontend-framework/02-elegir-el-framework-adecido' },
                    { label: '03 · Componentes: la pieza fundamental', link: '/apuntes-pi2/u2-frontend-framework/03-componentes-la-pieza-fundamental' },
                    { label: '04 · Gestionar el estado', link: '/apuntes-pi2/u2-frontend-framework/04-gestionar-el-estado' },
                    { label: '05 · Rendimiento y optimización', link: '/apuntes-pi2/u2-frontend-framework/05-rendimiento-y-optimizacion' },
                    { label: '06 · Accesibilidad web', link: '/apuntes-pi2/u2-frontend-framework/06-accesibilidad-web' },
                    { label: '07 · Probar la interfaz', link: '/apuntes-pi2/u2-frontend-framework/07-probar-la-interfaz' },
                    { label: '08 · Checklist de frontend', link: '/apuntes-pi2/u2-frontend-framework/08-checklist-de-frontend' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u2-frontend-framework/09-cierre' },
                  ],
                },
                {
                  label: '🔗 U3. Integrar sistemas',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u3-apis-rest' },
                    { label: '01 · Comunicación entre partes', link: '/apuntes-pi2/u3-apis-rest/01-comunicacion-entre-partes' },
                    { label: '02 · Definir la API', link: '/apuntes-pi2/u3-apis-rest/02-definir-la-api' },
                    { label: '03 · Contrato antes de codificar', link: '/apuntes-pi2/u3-apis-rest/03-contrato-antes-de-codificar' },
                    { label: '04 · Manejo de errores', link: '/apuntes-pi2/u3-apis-rest/04-manejo-de-errores' },
                    { label: '05 · Servicios externos', link: '/apuntes-pi2/u3-apis-rest/05-integrar-servicios-externos' },
                    { label: '06 · Seguridad en la comunicación', link: '/apuntes-pi2/u3-apis-rest/06-seguridad-en-la-comunicacion' },
                    { label: '07 · Herramientas de desarrollo', link: '/apuntes-pi2/u3-apis-rest/07-herramientas-de-desarrollo' },
                    { label: '08 · Checklist de integraciones', link: '/apuntes-pi2/u3-apis-rest/08-checklist-de-integraciones' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u3-apis-rest/09-cierre' },
                  ],
                },
                {
                  label: '👤 U4. Diseñar para el usuario',
                  collapsed: true,
                  items: [
                    { label: '📑 Índice', link: '/apuntes-pi2/u4-ui-ux' },
                    { label: '01 · UX no es "hacerlo bonito"', link: '/apuntes-pi2/u4-ui-ux/01-ux-no-es-hacerlo-bonito' },
                    { label: '02 · Principios de usabilidad', link: '/apuntes-pi2/u4-ui-ux/02-principios-de-usabilidad' },
                    { label: '03 · Accesibilidad para todos', link: '/apuntes-pi2/u4-ui-ux/03-accesibilidad-para-todos' },
                    { label: '04 · Diseño para móvil', link: '/apuntes-pi2/u4-ui-ux/04-diseno-para-movil' },
                    { label: '05 · Testing con usuarios', link: '/apuntes-pi2/u4-ui-ux/05-testing-con-usuarios' },
                    { label: '06 · Prototipado rápido', link: '/apuntes-pi2/u4-ui-ux/06-prototipado-rapido' },
                    { label: '07 · Microcopy y mensajes', link: '/apuntes-pi2/u4-ui-ux/07-microcopy-y-mensajes' },
                    { label: '08 · Checklist de usabilidad', link: '/apuntes-pi2/u4-ui-ux/08-checklist-de-usabilidad' },
                    { label: '09 · Cierre', link: '/apuntes-pi2/u4-ui-ux/09-cierre' },
                  ],
                },
                { label: '✅ U5. Asegurar la calidad', link: '/apuntes-pi2/u5-testing' },
                { label: '🛡️ U6. Proteger la aplicación', link: '/apuntes-pi2/u6-seguridad' },
                { label: '📦 U7. Preparar el despliegue', link: '/apuntes-pi2/u7-docker' },
                { label: '🚀 U8. Publicar y mantener', link: '/apuntes-pi2/u8-despliegue-ci-cd' },
                { label: '🔁 U9. Gestionar el proyecto', link: '/apuntes-pi2/u9-metodologias-agiles' },
              ],
            },
          ],
        },
      ],
    }),
    mdx(),
  ],
});
